apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-express-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-notifications
spec:
  project: default
  source:
    repoURL: https://github.com/ebenezermakinde/argocd-config.git
    targetRevision: HEAD
    path: dev/nodeapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: nodeepxress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false