apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-app
spec:
  selector:
    matchLabels:
      app: node-express-app
  replicas: 2
  template:
    metadata:
      labels: 
        app: node-express-app
    spec:
      containers:
      - name: node-express-app
        image: ebenezermakinde/node-express-app:6
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: node-express-app-service
spec:
  selector:
    app: node-express-app
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000