apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  selector:
    matchLabels:
      app: simpleapp
  replicas: 2
  template:
    metadata:
      labels: 
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: ebenezermakinde/simpleapp:126
        ports:
        - containerPort: 3500